#!/usr/bin/env python3

SAMPLERATE = 48000
DATATYPE = "float32"

SIGNAL_FREQUENCY = 1000
SIGNAL_MINUTE_MS = 500
SIGNAL_10SEC_MS = 160
SIGNAL_1SEC_MS = 80
SIGNAL_MORSE_CODE_SPACE_SEC = 10


ONE_MILLISECOND_FRAMES = int(SAMPLERATE / SIGNAL_FREQUENCY)

MORSE_CODE_FREQUENCY = 600
MORSE_CODE_DOT_DURATION = 60
