#!/usr/bin/env python3

SAMPLERATE = 48000
SIGNAL_FREQUENCY = 1000
DATATYPE = "float32"
ONE_MILLISECOND_FRAMES = int(SAMPLERATE / SIGNAL_FREQUENCY)

MORSE_CODE_FREQUENCY = 600
MORSE_CODE_DOT_DURATION = 60
